do $$
begin
  if not exists (select 1 from pg_type where typname = 'enum_products_stock_status') then
    create type public.enum_products_stock_status as enum (
      'IN_STOCK',
      'LOW_STOCK',
      'OUT_OF_STOCK'
    );
  end if;
end $$;

create table if not exists public.products (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  category varchar(80) not null,
  price numeric(10, 2) not null,
  stock_status public.enum_products_stock_status not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_name_idx
on public.products (name);

