create table if not exists public.admins (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(180) not null,
  password_hash varchar(255) not null,
  refresh_token_version integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists admins_email_unique_idx
on public.admins (email);

